name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, staging]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18'
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  # Quality checks - Linting, type checking, security
  quality:
    runs-on: ubuntu-latest
    name: Code Quality & Security
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Type checking
        run: npm run type-check

      - name: Lint code
        run: npm run lint

      - name: Security audit
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Check for vulnerabilities
        run: |
          npx audit-ci --config .audit-ci.json || echo "Vulnerabilities found but continuing..."

      - name: Dependency check
        run: |
          npx depcheck --ignores="@types/*,eslint-*,prettier,typescript"

  # Build and test
  test:
    runs-on: ubuntu-latest
    name: Build & Test
    needs: quality
    
    strategy:
      matrix:
        test-group: [unit, integration, e2e]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup test environment
        run: npm run test:setup

      - name: Run unit tests
        if: matrix.test-group == 'unit'
        run: |
          npm run test:unit -- --coverage --coverageReporters=lcov --coverageReporters=text
          
      - name: Run integration tests
        if: matrix.test-group == 'integration'
        run: npm run test:integration

      - name: Install Playwright browsers
        if: matrix.test-group == 'e2e'
        run: npx playwright install --with-deps

      - name: Build application
        if: matrix.test-group == 'e2e'
        run: npm run build

      - name: Run E2E tests
        if: matrix.test-group == 'e2e'
        run: npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.test-group }}
          path: |
            test-results/
            coverage/
            playwright-report/
          retention-days: 30

      - name: Upload coverage to Codecov
        if: matrix.test-group == 'unit'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  # Performance testing
  performance:
    runs-on: ubuntu-latest
    name: Performance Tests
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Start application
        run: npm start &
        env:
          NODE_ENV: production

      - name: Wait for server
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run performance tests
        run: npm run test:performance

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.12.0
          lhci autorun || echo "Lighthouse CI completed with warnings"
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: |
            .lighthouseci/
            performance-results/

  # Build for deployment
  build:
    runs-on: ubuntu-latest
    name: Build Application
    needs: [quality, test]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Generate standalone build
        run: |
          echo "Standalone build generated"
          ls -la .next/

      - name: Compress build artifacts
        run: |
          tar -czf build-artifacts.tar.gz .next/ public/ package*.json next.config.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz
          retention-days: 30

  # Security scanning
  security:
    runs-on: ubuntu-latest
    name: Security Scanning
    needs: quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: typescript, javascript

  # Deploy to staging
  deploy-staging:
    runs-on: ubuntu-latest
    name: Deploy to Staging
    needs: [build, security]
    if: github.ref == 'refs/heads/staging'
    environment:
      name: staging
      url: https://staging.yoursite.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Extract build artifacts
        run: tar -xzf build-artifacts.tar.gz

      - name: Deploy to Vercel staging
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Run smoke tests on staging
        run: |
          npx wait-on https://staging.yoursite.com --timeout 300000
          npm run test:e2e -- --grep "smoke"
        env:
          TEST_URL: https://staging.yoursite.com

  # Deploy to production
  deploy-production:
    runs-on: ubuntu-latest
    name: Deploy to Production
    needs: [build, security, performance]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://yoursite.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Extract build artifacts
        run: tar -xzf build-artifacts.tar.gz

      - name: Deploy to Vercel production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Run smoke tests on production
        run: |
          npx wait-on https://yoursite.com --timeout 300000
          npm run test:e2e -- --grep "smoke"
        env:
          TEST_URL: https://yoursite.com

      - name: Notify deployment success
        uses: 8398a7/action-slack@v3
        if: success()
        with:
          status: success
          text: '🚀 Production deployment successful!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify deployment failure
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: failure
          text: '❌ Production deployment failed!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Cleanup
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup
    needs: [deploy-staging, deploy-production]
    if: always()
    
    steps:
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v4
        with:
          name: |
            build-artifacts
            test-results-*
          skipIfNotFound: true